#!/bin/bash


echo ''
echo "Welcome to the onelife_easy_install. This installer was designed "
echo "and tested for Ubuntu 18.04. Please visit the following link"
echo "for documentation. If you wish to preform a more custom installation,"
echo "press Ctrl+c and execute the installer using \"./install walkthrough\"."
echo ''
echo "https://github.com/andrew-klassen/onelife_easy_install"
echo ''

# make sure user is root
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root." 
	exit 1
fi

# login info for ansible
read -p "Ssh username (needs sudo power): " ssh_username
read -s -p "Ssh password: " ssh_password

echo ''

if [[ $1 == "walkthrough" ]]; then	

	read -p "Max users (default: 160): " max_users
	read -p "Eve spawn position, fixed or random (default: fixed): " spawn_position
	
	# make sure using provided a correct response
	while [[ ${spawn_position} != "random" && ${spawn_position} != "fixed" && ${spawn_position} != "" ]]
	do 
		read -p "Eve spawn position, [fixed or random]: " spawn_position
	done

	read -p "Require login credentials: (default: false): " require_login

	# make sure using provided a correct response
	while [[ ${require_login} != true && ${require_login} != false && ${require_login} != "" ]]
        do
                read -p "Require login credentials [true or false]: " require_login
        done

	read -p "Turn on easy mode/less hungry? [yes or no] (default: no): " easy_mode

	# make sure using provided a correct response
	while [[ ${easy_mode} != "yes" && ${easy_mode} != "no" && ${easy_mode} != "" ]]
        do
		read -p "Turn on easy mode/less hungry? [yes or no] (default: no): " easy_mode
        done

	read -p "Server password (default: none): " server_password
	read -p "Port number (default: 8005): " port_number

fi


# skip installing ansible if already installed
if ! command -v ansible > /dev/null 2>&1; then

		apt-get update
		apt-get install software-properties-common -y
		add-apt-repository ppa:ansible/ansible -y
		apt-get update
		apt-get install ansible openssh-server -y

else

	echo ''
	echo ''
	echo "Ansible is installed. Skipping ansible Installation."

fi


cd ansible

if [[ $1 == "walkthrough" ]]; then

	if [[ -z "${max_users}" ]]; then
		max_users="160"
	fi
	if [[ ${spawn_position} == "random" ]]; then
		spawn_position="force_eve_location=0 eve_x=0 eve_y=0"
        fi
	if [[ $require_login ]]; then
		ticket_check="1"
	else
		ticket_check="0"
        fi
	if [[ ! -z "$server_password" ]]; then
		server_password="server_password=${server_password}"
        fi
	if [[ -z "${port_number}" ]]; then
                port_number="8005"
        fi
	if [[ -z "${easy_mode}" ]]; then
                easy_mode="no"
        fi

	ansible-playbook install.yml -e "ansible_user=${ssh_username} ansible_ssh_pass=${ssh_password} ansible_sudo_pass=${ssh_password} max_users=${max_users} ${spawn_position} ticket_check=${ticket_check} easy_mode=${easy_mode} ${server_password} port_number=${port_number}"
else
	ansible-playbook install.yml -e "ansible_user=${ssh_username} ansible_ssh_pass=${ssh_password} ansible_sudo_pass=${ssh_password}"	
fi
